# Início de uma jornada

Olá, querido leitor! Antes de entrarmos de fato nos assuntos relacionados ao dataset que iremos trabalhar, gostaria de me apresentar.

Meu nome é Ana Luiza Prata, tenho 24 anos e sou residente da cidade de Nova Iguaçu (RJ). Atualmente, eu estou no final da minha graduação em Engenharia Química na UFRRJ e inicianndo meus estudos na área de análise de dados.

Portanto, esse projeto é o meu primeiro de muitos que ainda virão. Graças à incrível imersão de dados da Alura, aprendi muito sobre diversas bibliotecas do Python e estou podendo desenvolver esse trabalho, dando o meu primeiro passo na construção de um portfólio para Data Science.

# O que iremos explorar?

Nesta edição da imersão de dados, a Alura propôs que explorássemos uma base de dados disponibilizada no site https://www.kaggle.com/ relacionada a estudos de **drug discovery**.

É bem clara a relevância dessas informações e estudos para a atual conjuntura que o mundo está vivendo: a pandemia do COVID-19. Já estamos em pouco mais de um ano no combate a esse vírus e, até o presente momento, já foram 3,55 milhões de mortes no mundo e zero tratamentos comprovadamente eficazes desenvolvidos.

Desenvolver drogas que sejam úteis no cambate à doença é um processo longo e que demanda muitos ensaios bioquímicos e clínicos. É uma verdadeira corrida contra o tempo.

(procurar as etapas do processo para colocar aqui)
(mostrar a relevância da análise de dados para esse caso)

É na fase inicial desse processo que iremos focar aqui nesse trabalho.

In [1]:
# Bibliotecas utilizadas

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

## Importando e compreendendo as bases de dados

In [3]:
url_dados1 = "https://github.com/anaprataa/imersao-dados-desafio-final/blob/main/Dados/dados_experimentos.zip?raw=true"
url_dados2 = "https://github.com/anaprataa/imersao-dados-desafio-final/blob/main/Dados/dados_resultados.csv?raw=true"

experimentos = pd.read_csv(url_dados1, compression='zip')
resultados = pd.read_csv(url_dados2)

display(experimentos.head())
display(resultados.head())

,id,tratamento,tempo,dose,droga,g-0,g-1,g-2,g-3,g-4,...,c-90,c-91,c-92,c-93,c-94,c-95,c-96,c-97,c-98,c-99
0,id_000644bb2,com_droga,24,D1,b68db1d53,1.0620,0.5577,-0.2479,-0.6208,-0.1944,...,0.2862,0.2584,0.8076,0.5523,-0.1912,0.6584,-0.3981,0.2139,0.3801,0.4176
1,id_000779bfc,com_droga,72,D1,df89a8e5a,0.0743,0.4087,0.2991,0.0604,1.0190,...,-0.4265,0.7543,0.4708,0.0230,0.2957,0.4899,0.1522,0.1241,0.6077,0.7371
2,id_000a6266a,com_droga,48,D1,18bb41b2c,0.6280,0.5817,1.5540,-0.0764,-0.0323,...,-0.7250,-0.6297,0.6103,0.0223,-1.3240,-0.3174,-0.6417,-0.2187,-1.4080,0.6931
3,id_0015fd391,com_droga,48,D1,8c7f86626,-0.5138,-0.2491,-0.2656,0.5288,4.0620,...,-2.0990,-0.6441,-5.6300,-1.3780,-0.8632,-1.2880,-1.6210,-0.8784,-0.3876,-0.8154
4,id_001626bd3,com_droga,72,D2,7cbed3131,-0.3254,-0.4009,0.9700,0.6919,1.4180,...,0.0042,0.0048,0.6670,1.0690,0.5523,-0.3031,0.1094,0.2885,-0.3786,0.7125

,id,5-alpha_reductase_inhibitor,11-beta-hsd1_inhibitor,acat_inhibitor,acetylcholine_receptor_agonist,acetylcholine_receptor_antagonist,acetylcholinesterase_inhibitor,adenosine_receptor_agonist,adenosine_receptor_antagonist,adenylyl_cyclase_activator,...,tropomyosin_receptor_kinase_inhibitor,trpv_agonist,trpv_antagonist,tubulin_inhibitor,tyrosine_kinase_inhibitor,ubiquitin_specific_protease_inhibitor,vegfr_inhibitor,vitamin_b,vitamin_d_receptor_agonist,wnt_inhibitor
0,id_000644bb2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,id_000779bfc,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,id_000a6266a,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,id_0015fd391,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,id_001626bd3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0